### ISSUE TITLE
USE SEPARATE BRANCH FOR UPDATES!

### ISSUE THREAD

**Issue by MCLiii** [sahuidhsu/monopoly_calculator#1]
Seriously, branch is nice, just try it out..
![conflict2](https://user-images.githubusercontent.com/57700505/177225362-ff9ec028-62b7-4877-b1d0-c3aed21745a6.jpg)
.

**Comment by sahuidhsu** [comment]
sure XDMingcan Li ***@***.***> 於 2022年7月5日 00:34 寫道：﻿
Seriously, branch is nice, just try it out..

.
